docs: update readme

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -8,7 +8,7 @@ if ! head -1 "$1" | grep -qE "^(build|chore|ci|docs|feat|fix|perf|refactor|rever
     echo "For more information check https://www.conventionalcommits.org/en/v1.0.0/ for more details" >&2
     exit 1
 fi
-if ! head -1 "$1" | grep -qE "^.{1,100}$"; then
-    echo "Aborting commit. Your commit message is too long." >&2
+if ! head -1 "$1" | grep -qE "^.{1,89}$"; then
+    echo "Aborting commit. Your commit message is too long. Max length is 89 characters" >&2
     exit 1
 fi
